# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longitude_parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logitude_latitude',
            old_name='long',
            new_name='longi',
        ),
    ]
